// 小学1年生 配当漢字 80字
// on: 音読み（カタカナ）, kun: 訓読み（ひらがな）
// label: 選択肢に表示する文字列

const KANJI_DATA = {
  1: [
    { kanji: '一', on: 'イチ・イツ', kun: 'ひと・ひとつ' },
    { kanji: '右', on: 'ウ・ユウ',   kun: 'みぎ' },
    { kanji: '雨', on: 'ウ',         kun: 'あめ・あま' },
    { kanji: '円', on: 'エン',       kun: 'まる・まるい' },
    { kanji: '王', on: 'オウ',       kun: 'おう' },
    { kanji: '音', on: 'オン・イン', kun: 'おと・ね' },
    { kanji: '下', on: 'カ・ゲ',     kun: 'した・しも・もと・さげる' },
    { kanji: '火', on: 'カ',         kun: 'ひ・ほ' },
    { kanji: '花', on: 'カ',         kun: 'はな' },
    { kanji: '貝', on: 'カイ',       kun: 'かい' },
    { kanji: '学', on: 'ガク',       kun: 'まなぶ' },
    { kanji: '気', on: 'キ・ケ',     kun: 'き' },
    { kanji: '九', on: 'キュウ・ク', kun: 'ここのつ・ここの' },
    { kanji: '休', on: 'キュウ',     kun: 'やすむ・やすまる' },
    { kanji: '玉', on: 'ギョク',     kun: 'たま' },
    { kanji: '金', on: 'キン・コン', kun: 'かね・かな' },
    { kanji: '空', on: 'クウ',       kun: 'そら・あく・あける・から' },
    { kanji: '月', on: 'ゲツ・ガツ', kun: 'つき' },
    { kanji: '犬', on: 'ケン',       kun: 'いぬ' },
    { kanji: '見', on: 'ケン',       kun: 'みる・みえる・みせる' },
    { kanji: '五', on: 'ゴ',         kun: 'いつつ・いつ' },
    { kanji: '口', on: 'コウ・ク',   kun: 'くち' },
    { kanji: '校', on: 'コウ',       kun: '' },
    { kanji: '左', on: 'サ',         kun: 'ひだり' },
    { kanji: '三', on: 'サン',       kun: 'みっつ・み・みつ' },
    { kanji: '山', on: 'サン',       kun: 'やま' },
    { kanji: '子', on: 'シ・ス',     kun: 'こ・ね' },
    { kanji: '四', on: 'シ',         kun: 'よっつ・よ・よつ' },
    { kanji: '糸', on: 'シ',         kun: 'いと' },
    { kanji: '字', on: 'ジ',         kun: 'あざ' },
    { kanji: '耳', on: 'ジ',         kun: 'みみ' },
    { kanji: '七', on: 'シチ',       kun: 'ななつ・なな' },
    { kanji: '車', on: 'シャ',       kun: 'くるま' },
    { kanji: '手', on: 'シュ',       kun: 'て・た' },
    { kanji: '十', on: 'ジュウ・ジッ',kun: 'とお・と' },
    { kanji: '出', on: 'シュツ・スイ',kun: 'でる・だす' },
    { kanji: '女', on: 'ジョ・ニョ', kun: 'おんな・め' },
    { kanji: '小', on: 'ショウ',     kun: 'ちいさい・こ・お' },
    { kanji: '上', on: 'ジョウ・ショウ',kun: 'うえ・うわ・かみ・あげる' },
    { kanji: '森', on: 'シン',       kun: 'もり' },
    { kanji: '人', on: 'ジン・ニン', kun: 'ひと' },
    { kanji: '水', on: 'スイ',       kun: 'みず' },
    { kanji: '正', on: 'セイ・ショウ',kun: 'ただしい・まさ' },
    { kanji: '生', on: 'セイ・ショウ',kun: 'いきる・うまれる・はえる' },
    { kanji: '青', on: 'セイ・ショウ',kun: 'あお・あおい' },
    { kanji: '夕', on: 'セキ',       kun: 'ゆう' },
    { kanji: '石', on: 'セキ・シャク・コク',kun: 'いし' },
    { kanji: '赤', on: 'セキ・シャク',kun: 'あか・あかい' },
    { kanji: '千', on: 'セン',       kun: 'ち' },
    { kanji: '川', on: 'セン',       kun: 'かわ' },
    { kanji: '先', on: 'セン',       kun: 'さき・まず' },
    { kanji: '早', on: 'ソウ・サッ', kun: 'はやい・はやまる' },
    { kanji: '草', on: 'ソウ',       kun: 'くさ' },
    { kanji: '足', on: 'ソク',       kun: 'あし・たりる・たす' },
    { kanji: '村', on: 'ソン',       kun: 'むら' },
    { kanji: '大', on: 'ダイ・タイ', kun: 'おおきい・おお' },
    { kanji: '男', on: 'ダン・ナン', kun: 'おとこ' },
    { kanji: '竹', on: 'チク',       kun: 'たけ' },
    { kanji: '中', on: 'チュウ',     kun: 'なか' },
    { kanji: '虫', on: 'チュウ',     kun: 'むし' },
    { kanji: '町', on: 'チョウ',     kun: 'まち' },
    { kanji: '天', on: 'テン',       kun: 'あめ・あま' },
    { kanji: '田', on: 'デン',       kun: 'た' },
    { kanji: '土', on: 'ド・ト',     kun: 'つち' },
    { kanji: '二', on: 'ニ',         kun: 'ふたつ・ふた' },
    { kanji: '日', on: 'ニチ・ジツ', kun: 'ひ・か' },
    { kanji: '入', on: 'ニュウ',     kun: 'いる・いれる・はいる' },
    { kanji: '年', on: 'ネン',       kun: 'とし' },
    { kanji: '白', on: 'ハク・ビャク',kun: 'しろ・しろい' },
    { kanji: '八', on: 'ハチ',       kun: 'やっつ・やつ・や' },
    { kanji: '百', on: 'ヒャク',     kun: 'もも' },
    { kanji: '文', on: 'ブン・モン', kun: 'ふみ・あや' },
    { kanji: '木', on: 'モク・ボク', kun: 'き・こ' },
    { kanji: '本', on: 'ホン',       kun: 'もと' },
    { kanji: '名', on: 'メイ・ミョウ',kun: 'な' },
    { kanji: '目', on: 'モク・ボク', kun: 'め・ま' },
    { kanji: '立', on: 'リツ・リュウ',kun: 'たつ・たてる' },
    { kanji: '力', on: 'リョク・リキ',kun: 'ちから' },
    { kanji: '林', on: 'リン',       kun: 'はやし' },
    { kanji: '六', on: 'ロク',       kun: 'むっつ・む・むつ' },
  ]
  // 2年生以降はここに追加
};

// 学年情報
const GRADE_INFO = {
  1: { label: '1年生', count: 80,  color: '#FF8C69', available: true  },
  2: { label: '2年生', count: 160, color: '#4CAF50', available: false },
  3: { label: '3年生', count: 200, color: '#2196F3', available: false },
  4: { label: '4年生', count: 200, color: '#9C27B0', available: false },
  5: { label: '5年生', count: 185, color: '#FF5722', available: false },
  6: { label: '6年生', count: 181, color: '#795548', available: false },
};
